/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Numbers {
    static int sumFirstNRec(int n) {
        if (n <= 0) {
            return 0
        } else {
            return n + sumFirstNRec(n - 1)
        }
    }

    static int factorialRec(int n) {
        if (n <= 1) {
            return 1
        } else {
            return n * factorialRec(n - 1)
        }
    }

    static int fibonacciRec(int n) {
        if (n <= 1) {
            return n
        } else {
            return fibonacciRec(n - 1) + fibonacciRec(n - 2)
        }
    }

    static int greatestCommonDivisorRec(int a, int b) {
        if (b == 0) {
            return a
        } else {
            return greatestCommonDivisorRec(b, a % b)
        }
    }

    static int leastCommonMultipleRec(int a, int b) {
        return (a * b) / greatestCommonDivisorRec(a, b)
    }

    int sumFirstNAcc(int n){
        return sumFirstNHelp(n,0)
    }

    private int sumFirstNHelp(int n, int accumulator) {
        if(n <= 0){
            return accumulator
        } else {
            return sumFirstNHelp(n - 1, accumulator + n)
        }
    }

    int factorialAcc(int n) {
        return factorialAccHelp(n,1)
    }

    private int factorialHelp(int n, int accumulator) {
        if(n <= 0){
            return accumulator
        } else {
            return factorialHelp(n - 1, accumulator * n)
        }
    }

    int fibonacciAcc(int n) {
        return fibonacciAccHelp(n, 0, 1)
    }

    private int fibonacciHelp(int n, int acc2, int acc1) {
        if(n <= 0){
            return acc2
        } else {
            return fibonacciHelp(n - 1, acc1, acc2 + acc1)
        }
    }

    static int sumFirstNIte(int n) {
        int accumulator = 0;
        for(int i = 1; i <= n; i++) {
            accumulator += i;
        }
        return accumulator
    }

    static int factorialIte(int n) {
        int accumulator = 1;
        for(int i = 2; i <= n; i++) {
           accumulator *= i;
        }
        return accumulator
    }

    static int fibonacciIte(int n) {
        if (n <= 0) {
            return 0
        }
        int acc2 = 0,acc1 = 1;
        for(int i = 2; i <= n; i++) {
            int temp = acc1 + acc2
            acc2 = acc1
            acc1 = temp
        }
        return acc1
    }

    static int greatestCommonDivisorIte(int a, int b) {
        while(b != 0){
            int temp = b
            b = a % b
            a = temp
        }
        return a
    }

    static int leastCommonMultipleIte(int a, int b) {
        return (a * b) / greatestCommonDivisorIte(a,b)
    }
}
