/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import spock.lang.Specification

class NumbersRecTest extends Specification {
    def "Sum First N Rec"() {
        expect:
        Numbers.sumFirstNRec(0) == 0
        Numbers.sumFirstNRec(3) == 6
    }

    def "Factorial Rec"() {
        expect:
        Numbers.factorialRec(0) == 1
        Numbers.factorialRec(4) == 24
    }

    def "Fibonacci Rec"() {
        expect:
        Numbers.fibonacciRec(0) == 0
        Numbers.fibonacciRec(1) == 1
        Numbers.fibonacciRec(6) == 8
    }

    def "GCD Rec"() {
        expect:
        Numbers.greatestCommonDivisorRec(12, 8) == 4
        Numbers.greatestCommonDivisorRec(7, 5) == 1
    }

    def "LCM Rec"() {
        expect:
        Numbers.leastCommonMultipleRec(6, 8) == 24
        Numbers.leastCommonMultipleRec(6, 4) == 12
    }
}
