/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import spock.lang.Specification

class NumbersIteTest extends Specification {
    def "Sum First N Ite"() {
        expect:
        Numbers.sumFirstNIte(0) == 0
        Numbers.sumFirstNIte(3) == 6
    }

    def "Factorial Ite"() {
        expect:
        Numbers.factorialIte(0) == 1
        Numbers.factorialIte(4) == 24
    }

    def "Fibonacci Ite"() {
        expect:
        Numbers.fibonacciIte(0) == 0
        Numbers.fibonacciIte(1) == 1
        Numbers.fibonacciIte(6) == 8
    }

    def "GCD Ite"() {
        expect:
        Numbers.greatestCommonDivisorIte(12, 8) == 4
        Numbers.greatestCommonDivisorIte(7, 5) == 1
    }

    def "LCM Ite"() {
        expect:
        Numbers.leastCommonMultipleIte(6, 8) == 24
        Numbers.leastCommonMultipleIte(6, 4) == 12
    }
}
