/*
 * This source file was generated by the Gradle 'init' task
 */
package data_structures_basics

import spock.lang.Specification

class DataStructuresBasicsTest extends Specification {
    def "someLibraryMethod returns true"() {
        setup:
        def lib = new DataStructuresBasics()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
